name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main       
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy with Password
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🚀 Deploy with Password
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 22
          local_path: '.'
          remote_path: '/dulceproposito'
          sftp_only: true
          exclude: |
            .git*
            README.md
